name: pharmacist_mobile
description: "A pharmacy management app"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  dartz: ^0.10.1
  internet_connection_checker: ^3.0.1
  shared_preferences: ^2.5.3
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/dummy_medicines.json
